### PR TITLE
logo adjustments, menu adjustments, node menu fix

### LINKED ISSUE #436: Make Cogeco logo a bit clearer
We have the Cogeco logo in the corner of the app since they've funded development of the app. In 1.0 it was more noticeable, but faded down a bit while you were interacting with the map. This seems to have gone away and now it's always very faded - can we bring back the old behaviour?

### LINKED ISSUE #454: Black dividers between menu items disappear on tap
You can see this when you tap an item in the "i" menu - the black dividers disappear briefly.

### LINKED ISSUE #457: Selected node should reappear once INFO menu is gone

### PR DESCRIPTION
**Pull request by jotkali**
- logo to .045 transparency. 
- logo position adjustment
- different visual treatment of menus.
- selected INFO menu longer resets globe, in order to keep selected node state
- deleted old icons from project folder
- handle ASN "is not valid" return from server

fixes #454
fixes #436 
fixes #457

### CODE REVIEW

File: iOS/NodeSearchViewController.m [hunk 1]
```diff
@@ -197,10 +201,18 @@ - (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(N
 
 - (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath {
     
+    
+
+    
+    /*
```
Comment (apike) [inline iOS/NodeSearchViewController.m]: If we don't want this code anymore, let's remove it

**Comment by apike** [comment]
:+1:
