### PR TITLE
AR node selection and sizing

### LINKED ISSUE #525: Make nodes more reasonably smaller without making them too hard to tap
There's something subtly wrong with the logic for selecting nodes, such that nodes are much harder to select than in seems like they should be. Could be some artifact of touch positions being too inaccurate or the bucketing of nodes into grid cells for optimization. 

Problem gets worse as the node size gets smaller, we want to make the nodes a fair bit smaller for the AR mode, but the smaller they get, the harder it is to actually pick one.

### LINKED ISSUE #544: Fully reload visualization when switching modes
Right now the AR only visualization parameters (node size, for example) don't get picked up when switching into AR mode.

### PR DESCRIPTION
**Pull request by nbrooke**
This fixes #525 and fixes #544.

Nodes that were between the near clip plane and z = -0.1we visible but not selectable, so as you moved closer to small nodes, you'd stop being able to select them (any node within 10cm of the camera).

This also fixes an issue where the difference in node size between AR and non-AR wasn't always picked up, and sets the node scale for AR to the desired value of 0.5

### CODE REVIEW

File: iOS/ViewController.m [hunk 1]
```diff
@@ -356,12 +356,10 @@ - (void)setARMode:(ARMode)mode {
     self.arEnabled = mode != ARModeDisabled;
     self.arMode = mode;
 
-    if(!wasEnabled && self.arEnabled) {
-        [self forceResetView];
-    }
-
-    if(wasEnabled && !self.arEnabled) {
+    if(wasEnabled ^ self.arEnabled) {
```
Comment (robmaceachern) [inline iOS/ViewController.m]: Had to look up what `wasEnabled ^ self.arEnabled` was :)

Comment (nbrooke) [reply iOS/ViewController.m]: I just realized that in this case != is actually does the same thing, some pattern matching part of my brain went "oh, that's an exclusive or", which is true, but not super useful here. I'll change it to be a bit less opaque.
