### PR TITLE
safari view controllers, auto layout fix for splash screens, and "map of internet" title sizing for small phones

### LINKED ISSUE #422: Load screen on iPhone doesn't show background, on iPad doesn't show image

### LINKED ISSUE #424: Show toolbars in Safari view controllers
The standard Safari View Controller has some toolbars so users can share the URL, etc. They're not pretty but they're probably better than doing our own custom X and not being able to (for example) share the URL.

### PR DESCRIPTION
**Pull request by jotkali**
Use safari view controllers for contact and open source
Tweaks on layout and font sizing

note : the contact us screen shows an ad on top of page

fix #422 
fix #424

### CODE REVIEW

File: iOS/ViewController.m [hunk 1]
```diff
@@ -662,6 +654,15 @@ -(IBAction)infoButtonPressed:(id)sender {
             [self.infoPopover setPopoverContentSize:CGSizeMake(340, 175)];
         }
         
+        
+        
+        /*
+         NSURL *url = [NSURL URLWithString:@"https://www.cogecopeer1.com/contact/"];
```
Comment (apike) [inline iOS/ViewController.m]: If we don't need this anymore let's remove it.

File: iOS/ViewController.m [hunk 2]
```diff
@@ -670,12 +671,32 @@ -(IBAction)infoButtonPressed:(id)sender {
                     [self showFirstUse];
                     break;
                 case 1: //sales
-                    [self showContactFormWithUrl:@"https://www.cogecopeer1.com/contact/"];
+                {
+                    NSURL *url = [NSURL URLWithString:@"https://www.cogecopeer1.com/contact/"];
+                    SFSafariViewController *safariView = [[SFSafariViewController alloc] initWithURL:url];
+                    safariView.modalPresentationStyle = UIModalPresentationOverFullScreen;
```
Comment (apike) [inline iOS/ViewController.m]: Let's avoid copy/pasting between these cases.

Comment (jotkali) [inline iOS/ViewController.m]: @apike Yup, that was lazy. Cleaned up.
